### ISSUE TITLE
Change favicon with different pages

### ISSUE THREAD

**Issue by jpsc** [expressjs/serve-favicon#15]
I'm creating a template based express app and I want to change the favicon according with the different template selected. Is this possible with serve-favicon ?

**Comment by Charuru** [comment]
@dougwilson hi sorry I know this is very old but can you explain what the difference is. Is it not possible to serve one main favicon with the server and then link different remote favicons and cache them as needed depending on route?

**Comment by dougwilson** [comment]
Not that I know of but I'm happy if you can show otherwise :+1: the web browsers control what is possible generally, and if something is possible that can be implemented in this module, I'd be happy to accept a pull request with the feature.
