### ISSUE TITLE
Support Requirement for Multiple Favicons

### ISSUE THREAD

**Issue by crispen-smith** [expressjs/serve-favicon#22]
Given that there are different requirements for all environments (Apple mobile, Windows, windows mobile etc.) is it possible to either a) document the best way to handle this in Express/serve-favicon or b) update the module to handle this use case.

    The best (most robust) mark-up seems to be:
    <link rel="apple-touch-icon" sizes="57x57" href="/apple-touch-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="114x114" href="/apple-touch-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="72x72" href="/apple-touch-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="144x144" href="/apple-touch-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="60x60" href="/apple-touch-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="120x120" href="/apple-touch-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="76x76" href="/apple-touch-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="152x152" href="/apple-touch-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon-180x180.png">
    <link rel="icon" type="image/png" href="/favicon-192x192.png" sizes="192x192">
    <link rel="icon" type="image/png" href="/favicon-160x160.png" sizes="160x160">
    <link rel="icon" type="image/png" href="/favicon-96x96.png" sizes="96x96">
    <link rel="icon" type="image/png" href="/favicon-16x16.png" sizes="16x16">
    <link rel="icon" type="image/png" href="/favicon-32x32.png" sizes="32x32">
    <meta name="msapplication-TileColor" content="#60000c"> 
   <meta name="msapplication-TileImage" content="/mstile-144x144.png">

It's currently unclear if all of these icons will resolve based on serve-favicon alone and I'm pretty sure that a solution could be arranged using static, it would be great if there's a way to configure serve-favicon so that it's readily apparent that paths to all of these files were made available via serve-favicon.

Ready to help in any way that I can.

**Comment by dougwilson** [comment]
So, this module _only_ caters to the favicon case that does not require any HTML markup. The main reason is that all browsers will _unconditionally_make a request for `/favicon.ico`, unlike the other ones listed above and that `/favicon.ico` requires a different `Content-Type` than what a `.ico` file is served with, making serving `favicon.ico` unreliable when using a static file server.

For what you listed above, why not just places all those in a directory and use something like `serve-static`?

**Comment by crispen-smith** [comment]
I agree that this is a sensible solution, but I think that at least speaking to it in docs may be worthwhile.  While the Express core team knows this very well I suspect that I'm not the only one who tripped // will trip over this.

**Comment by dougwilson** [comment]
It's no problem. If you have anything specific in mind, I'll always gladly take a PR, even doc changes :)

**Comment by crispen-smith** [comment]
Submitted. :)
