### ISSUE TITLE
serving different favicon for different pages

### ISSUE THREAD

**Issue by nallown** [expressjs/serve-favicon#26]
It would be useful to add the ability to allow us to serve a favicon directly from the controller it self so for example on the homepage you'd use the default global favicon and on the user page you may use a different favicon.

**Comment by dougwilson** [comment]
This module only follows a standard, which only allows you to define _one_ icon at the exact path `/favicon.ico`. Anything else requires JavaScript to HTML and is beyond the scope of that spec.
