### ISSUE TITLE
Possible to use location outside of your repo?

### ISSUE THREAD

**Issue by dstroot** [expressjs/serve-favicon#28]
Something like this?

```
app.use(favicon('https://d1ir1l1v07ijd0.cloudfront.net/img/ico/favicon.ico'));
```

**Comment by dougwilson** [comment]
So the quest is, possible to use something that the Node.js `fs` module cannot read? It is, since this module will also accept a `Buffer`, so you can write code to make an HTTP request and then instantiate this module with the resulting `Buffer`.

**Comment by dstroot** [comment]
Doug - you are wicked fast!  If you help me with an example of that I will submit a PR to document it in the readme.  Deal?  I'm not a buffer/streams guy ... yet.

**Comment by dougwilson** [comment]
No problem :) Perhaps you just always catch me at a time that I'm ready to respond ;)
```js
var express = require('express')
var getRawBody = require('raw-body')
var https = require('https')
var serveFavicon = require('serve-favicon')

createApp(function (err, app) {
  app.listen(3000, function (err) {
    if (err) throw err
    console.log('Express listening on port 3000')
  })
})

function getRemoteContent(url, callback) {
  var req = https.get(url)

  req.once('error', callback)
  req.on('response', function (res) {
    getRawBody(res, callback)
  })
}

function createRemoteServeFavicon(url, callback) {
  getRemoteContent(url, function (err, buf) {
    if (err) return callback(err)
    callback(null, serveFavicon(buf))
  })
}

function createApp(callback) {
  var app = express()

  createRemoteServeFavicon('https://d1ir1l1v07ijd0.cloudfront.net/img/ico/favicon.ico', function (err, favicon) {
    if (err) return callback(err)

    app.use(favicon)

    populateRoutes(app)

    callback(null, app)
  })
}

function populateRoutes(app) {
  app.get('/', function (req, res) {
    res.send('hello, world')
  })
}
```

> I will submit a PR to document it in the readme. 

I wouldn't accept a PR of the above extremely complex example (it's so complex because Node.js does not allow for sync network calls). I'll still add an example of "getting a Buffer from somewhere".

**Comment by dstroot** [comment]
Wow!  Thanks Doug!
