### ISSUE TITLE
Can't see favicon when using Microsoft Edge

### ISSUE THREAD

**Issue by bennyyip** [expressjs/serve-favicon#30]
I copy the example code in the README, it works well in Chrome and IE, but fail to show favicon in Edge

**Comment by dougwilson** [comment]
Searching for your issue on the web seems to indicate Edge does not show the favicon for sites loaded from localhost. Are you trying the example from localhost or from your remote server?

**Comment by bennyyip** [comment]
@dougwilson Thanks, this is exactly why Edge does not show the favicon
