### ISSUE TITLE
Vary favicon by domain

### ISSUE THREAD

**Issue by danielflippance** [expressjs/serve-favicon#31]
I serve multiple domains from a single Express app and would like to be able to change the favicon for each domain. ie: I want to vary the image file I choose to pass to favicon() based on req.hostname. The hostnames are chosen by the users and are sometimes only different by the sub-domain.

I can't see a way to vary the favicon chosen based on req.hostname and reading this [issue](https://github.com/expressjs/serve-favicon/issues/26) it seems there may not be a way to do so.

**Comment by dougwilson** [comment]
I'm not 100% sure I understand what you're trying to do? Do you think whipping up a proposal PR would help?

**Comment by danielflippance** [comment]
Good plan. I've added PR #32 as a potential implementation

**Comment by blakeembrey** [comment]
Could you do this? Just a thought based on the current usage pattern in the README.

```js
var exampleIcon = favicon(...);
var defaultIcon = favicon(...);

app.use(function (req, res, next) {
  if (req.hostname === 'example.com') {
    return exampleIcon(req, res, next);
  }

  return defaultIcon(req, res, next);
});
```

**Comment by dougwilson** [comment]
Conversation conclusion in the PR: https://github.com/expressjs/serve-favicon/pull/32#issuecomment-260845762
