### ISSUE TITLE
Doubts on res._headers

### ISSUE THREAD

**Issue by luokuning** [expressjs/serve-favicon#33]
Hi there,  I saw  `res._headers` in https://github.com/expressjs/serve-favicon/blob/master/index.js#L167,  but I have found nothing about that in [Node.js](https://nodejs.org/api/synopsis.html) documentation. Here are my test code on `res._headers`:

Node.js:
``` javascript
http.createServer((req, res) => {
  res.setHeader('Content-Type', 'application/json')
  console.log(res._headers) // { 'content-type': 'application/json' }
  res.end('done')
}).listen(9000)
```

curl(1): `curl localhost:9000`

So I guess `res._headers` represent all headers that set by `res.setHeader` method, am I right?

**Comment by tj** [comment]
yep, unfortunately there isn't (or wasn't at least) a `res.headers` equivalent to `req.headers`

**Comment by dougwilson** [comment]
Yes, @luokuning, the `_headers` property is an internal Node.js map of all headers as lower-case keys to their values. This is not in their documentation because it is not a public API. This module uses that because Node.js has no public API to enumerate all headers set on the response object.

**Comment by luokuning** [comment]
Got it, many thanks! 😄
