### ISSUE TITLE
Favicon not showing when running server with long context path.

### ISSUE THREAD

**Issue by kol9n93** [expressjs/serve-favicon#34]
Hi. Favicon is showing when I run server locally with express (http://localhost:3000). But when I run it on production server (http://test.server.com/prod-test/myapp), It isn't working at all.

**Comment by dougwilson** [comment]
Your app must be at the root of your domain, from the readme.

**Comment by kol9n93** [comment]
Is there some workaround?

**Comment by dougwilson** [comment]
You can read that Wikipedia article; the web browsers only ever load GET /favicon.ico so the file needs to be at the root. If there is a way to change the web browsers to load it from another URL then you could probably do that. This module is limited by how the web browsers work, and they want the icon served up at the root path.

**Comment by dougwilson** [comment]
Basically check out that table in the Wikipedia article and you just need to add a link tag to every page in your web site that specifies the alternative URL.

**Comment by kol9n93** [comment]
Thank you for your help.
