### ISSUE TITLE
how can I use a url instead of path?

### ISSUE THREAD

**Issue by hadifarnoud** [expressjs/serve-favicon#37]
as I understand this package gets local path for favicon. what if my favicon is at `http://domain.com/favicon.ico`? 

I can't give it this string as path.

**Comment by mauricionr** [comment]
:+1: any guess?

**Comment by dougwilson** [comment]
You can't. See the module's description including the link to Wikipedia regarding what can be done. Web browsers will automatically make a request to `GET /favicon.ico`, so you need to serve the icon up at that address for the browser to get it. If you don't want to keep the icon file on your local file system, you can always use the `request` module or similar to fetch the icon on your server, and then provide the `Buffer` object to this module as the icon.

**Comment by hadifarnoud** [comment]
@dougwilson I tried doing that and failed. Asked a few people too but we were not able to get it to work.

can you kindly provide an example? I had to write the whole thing without your package but would be nice to switch

**Comment by dougwilson** [comment]
Something like this:
```js
module.exports = createApp (cb) {
  var app = express();

  // ... do setup / add things

  request({ method: 'GET', url: 'http://example.com/favicon.ico', encoding: null}, function (err, res, body) {
    if (err) return cb(err);

    app.use(serveFavicon(body));

    // .. continute to setup app

    cb(null, app);
  });
};
```
