### ISSUE TITLE
Favicon is not showing

### ISSUE THREAD

**Issue by Azam2926** [expressjs/serve-favicon#40]
Favicon **is not showing** except `http://localhost:3000/` rout

**Comment by dougwilson** [comment]
Hi @Azam2926 I'm sorry to hear that. Please provide more information so we can reproduce the issue and take a look !

**Comment by Azam2926** [comment]
Hello **@dougwilson**. Sorry sorry. I wrote other view of routes like that    ` link(rel="icon" href="../itutor/iTutor.ico" type='image/x-icon')` so that icon is not showing.  Once again **sorry** for your **dissatisfaction**

**Comment by Azam2926** [comment]
Now it absolutly is working 🌝

**Comment by dougwilson** [comment]
Hi @Azam2926 it's no problem at all. I'm glad you got it working 👍
