### ISSUE TITLE
Can't run express js server app on my local host:3000

### ISSUE THREAD

**Issue by 3abdawy** [expressjs/serve-favicon#41]
The browser keeps showing an error says :-
> for the favicon.ico automatic Get request by the browser 
1) Refused to load the image 'http://localhost:3000/favicon.ico' because it violates the following Content Security Policy directive: "default-src 'none'". Note that 'img-src' was not explicitly set, so 'default-src' is used as a fallback.

> for my localhost Get request
1) it returns with 404 error Not found

**Comment by dougwilson** [comment]
Very strange. I am not able to reproduce the issue just using the example in the readme.

Can you provide all the following?

1. Browser you are using
2. Node.js version
3. Version of this module
4. Complete code I can run that reproduces the issue
5. Instructions for how to reproduce

Thanks!

**Comment by 3abdawy** [comment]
1) Chrome latest version
2) Node v13.5.0
3) i will attach the project files ('its a simple one using express.js')
4) u need to install dependencies ('npm install') and run the app.js with node ('node app.js').
 It always show me an error concerning content-security-policy , however i added the headers to skip the cors problem , and also i used disable csp extension to make sure that i'm not exposed to any csp concerns , thats worked for the favicon but still cannot find my localhost:3000 with error 404 not found ! 
Thanks in advance !

**### app.js file**
const express = require('express');
const bodyParser = require('body-parser');
const csp = require('express-csp-header');
// const favicon = require('serve-favicon');
const locationRoutes = require('./routes/location');
const app = express();
app.use(bodyParser.json());

app.use((req, res, next) => {
    res.setHeader('Access-Control-Allow-Origin', '*');
    res.setHeader('Access-Control-Allow-Methods', 'POST, GET, OPTIONS');
    res.setHeader('Access-Control-Allow-Headers', 'Content-Type');
    next();
});

app.use(locationRoutes);

app.listen(3000);

**### location.js** in **routes** folder
const express = require('express');

let router = express.Router();

const locationStorage = {
    locations: [ ]
};

router.get('/favicon.ico', (req, res) => res.sendStatus(200));

router.post('/add-location', (req, res, next) => {
    locationStorage.locations.push({
        id: Math.random(),
        address: req.body.address,
        coords: { lat: req.body.lat, lng: req.body.lng }
    });
    // res.sendStatus(200);
    res.json({message: 'Stored location!'});
});

router.get('/location', (req, res, next) => {});

module.exports = router;

****package.json** created by (node init )**
{
  "name": "trial",
  "version": "1.0.0",
  "description": "",
  "main": "app.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "body-parser": "^1.19.0",
    "express": "^4.17.1",
    "express-csp-header": "^2.3.2",
    "serve-favicon": "^2.5.0"
  }
}

**Comment by dougwilson** [comment]
Thanks. You are not actually using this module in your example, so this module would not actually have any effect on the issue you are having. If you are having a general express issue, you can always post of the express tracker.

**Comment by 3abdawy** [comment]
Thank you !

**Comment by dougwilson** [comment]
No problem. The audience is larger there and will make sure you get an answer :)
