### ISSUE TITLE
Feature Request: Serve icon based on host mapping

### ISSUE THREAD

**Issue by rcollette** [expressjs/serve-favicon#43]
We have a white label application that serves up the same application but branded for multiple customers. It would be great if this would serve up a different favicon based on what host is currently being called.  Perhaps a callback would be the most flexible mechanism as that would keep the library implementation simpler.  Cacheing might be keyed on the path that is returned by the callback.

**Comment by dougwilson** [comment]
How does your white labeling work? Can you just combine this with vhost module to achieve?

**Comment by rcollette** [comment]
You are correct.  Vhost would suffice for this.

We don't use vhost currently because Okta Middleware for Node does not work with it currently.

https://github.com/okta/okta-oidc-js/issues/497

I am going to close this issue.
