### ISSUE TITLE
Doesn't work with Chrome

### ISSUE THREAD

**Issue by misuedkaAtQuanos** [expressjs/serve-favicon#47]
It works with Firefox/Edge. It doesn't work with Chrome (Windows/Android, latest versions).

This works (creates a lot of favicon variants)
https://www.favicon-generator.org/

**Comment by dougwilson** [comment]
Hello, and sorry for any trouble. Can you expand on what doesn't work, exactly? Perhaps some replication steps so we can try and figure out what is going on? This module just takes the icon you give it and serves it at the path `/favicon.ico`; if you need to include any specific HTML that is of course beyond what this module can add for you, though you can point it to the path thia module seves it under (and get the benefits of zero disk access still).

**Comment by misuedkaAtQuanos** [comment]
Hi, there's little more I can add here.
I created a favicon.ico from an image with one of these favicon pages which you find by Goodle search. I can't remember exactly which one it was.  It created a 48x48 favicon.ico (I would have attached it here but file attachment here seem to be not possible). 
I installed your npm module and added it using the Express sample code. It showed up immediately on Firefox and Edge. But no success on Chrome even after a lot of reloading and Cache refresh hazzle. There even was no request for the icon visible in Dev tools.
Then I tried the page referenced in my first comment which created a lot of file variants and proposed a lot of  link entries as well, which I all added to my app. Doing so it worked immediately. In the screenshot below you see that Chrome (here: Windows) requests one of the file variants rather than favicon.ico.
Hope this helps. Thanks for your interest!

![image](https://github.com/expressjs/serve-favicon/assets/134615959/b105d796-2e78-445e-9dff-e241c20b71a4)

**Comment by dougwilson** [comment]
Gotcha. Unfortunately it sounds like that is just out of scope of thia module. At the top of thw readme it notea that this is only for the favicon.ico file and any additional files of HTML markup, you'll want to use serve-static module.

**Comment by misuedkaAtQuanos** [comment]
I read your README note again (and actually now I understand the impact) and understand your point. 
I just want to add my personal opinion that from a user's point of view, a solution which doesn't work for the typical browsers like Chrome is NOT a true solution, even if in earlier times the plain favicon.ico file might have been the solution for all browsers. Shame for Chrome if they might have things complicated since then, but ..., 
It would users save time, if you would change your note in the sense that today just serving the favicon,ico is no longer sufficient for working with all browsers. So interested users could then immediately head to other solution pages.

Thanks for clearing this up.
